[program:absensismkn8-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/absensismkn8/artisan queue:work --queue=default,notifications,exports,analytics --sleep=2 --tries=3 --backoff=10 --timeout=120 --max-time=3600 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/absensismkn8/storage/logs/worker.log
stopwaitsecs=3600
